#!/usr/bin/env python

'''
    Webserver for the IoT-Dashboard
    
    This app will connect to IoT devices and feed the WEB interface using Websocket API

    Requirements: 
        - tornado

    (c) 2014 - 2015 - 2016
    Ciro Scognamiglio <ciro.scognamiglio@lip6.fr>
    Loïc Baron <loic.baron@lip6.fr>
'''

import sys
import os
import logging

from tornado import web, ioloop

from iotDashboard import templates, static
from iotDashboard.protocols import rest, websocket
from iotDashboard.controllers import home

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
                    datefmt="%Y-%m-%d %H:%M:%S",
                    filename="iotDashboard.log", filemode="a")

if __name__ == '__main__':

    print "Starting web thread"

    app = web.Application([
        (r'/', home.Index),
        (r'/static/(.*)', web.StaticFileHandler, {'path': static}),

        (r'/ws', websocket.Api)

    ], template_path = templates)

    app.listen(8000)


    try :
        ioloop.IOLoop.instance().start()
    except KeyboardInterrupt:
        ioloop.IOLoop.instance().stop()
    except Exception as e:
        print e
        exit(1)

